export { HeroSection } from "./HeroSection";
export { IntegrationsSection } from "./IntegrationsSection";
export { SocialProofSection } from "./SocialProofSection";
export { SpeedComparisonSection } from "./SpeedComparisonSection";
export { UserTypesSection } from "./UserTypesSection";
export { SolutionSection } from "./SolutionSection";
export { PlatformSection } from "./PlatformSection";
export { AskAISection } from "./AskAISection";
export { FinalCTASection } from "./FinalCTASection";
